name: deploy 2 EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ EXE_METER_EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600  ~/.ssh/id_ed25519

      - name: Deploy EC2-1A
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_SSH_IP_1A }} << 'EOF'
            cd /var/www/exe_meter
            git pull origin main
            bundle install --without development test
            RAILS_ENV=production rails db:migrate
            sudo systemctl restart puma
          EOF
      
      - name: Deploy to EC2 1C
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_SSH_IP_1C }} << 'EOF'
            cd /var/www/exe_meter
            git pull origin main
            bundle install --without development test
            RAILS_ENV=production rails db:migrate
            sudo systemctl restart puma
          EOF

